// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hgYa2chxELsjCrsDiarb3T
// Component: T64UjHkK2R
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: whnP1U9nG_tYGg/component

import { useScreenVariants as useScreenVariantscvQoPsTOivAmc4 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: CVQoPsTOivAmc4/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_www_presell_ai.module.css"; // plasmic-import: hgYa2chxELsjCrsDiarb3T/projectcss
import sty from "./PlasmicSignUpV2.module.css"; // plasmic-import: T64UjHkK2R/css

import ChevronRightIcon from "./icons/PlasmicIcon__ChevronRight"; // plasmic-import: Yq9TX85itfl8Tl/icon
import Searchsvg2Icon from "./icons/PlasmicIcon__Searchsvg2"; // plasmic-import: GqlQDoqakuGAAn/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: q1JO1GFRPkcbBU/icon

export type PlasmicSignUpV2__VariantMembers = {};
export type PlasmicSignUpV2__VariantsArgs = {};
type VariantPropType = keyof PlasmicSignUpV2__VariantsArgs;
export const PlasmicSignUpV2__VariantProps = new Array<VariantPropType>();

export type PlasmicSignUpV2__ArgsType = {};
type ArgPropType = keyof PlasmicSignUpV2__ArgsType;
export const PlasmicSignUpV2__ArgProps = new Array<ArgPropType>();

export type PlasmicSignUpV2__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
  form?: p.Flex<"form">;
};

export interface DefaultSignUpV2Props {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicSignUpV2__RenderFunc(props: {
  variants: PlasmicSignUpV2__VariantsArgs;
  args: PlasmicSignUpV2__ArgsType;
  overrides: PlasmicSignUpV2__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantscvQoPsTOivAmc4()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicSignUpV2.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicSignUpV2.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicSignUpV2.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__kwat2)}>
            <div className={classNames(projectcss.all, sty.columns__enP5J)}>
              {(
                hasVariant(globalVariants, "screen", "mobile") ? true : true
              ) ? (
                <div
                  className={classNames(projectcss.all, sty.column__tu8Ue)}
                />
              ) : null}

              <div className={classNames(projectcss.all, sty.column__oqBot)}>
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__j4Jye)}
                  >
                    {(
                      hasVariant(globalVariants, "screen", "mobile")
                        ? true
                        : true
                    ) ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___8O3I
                        )}
                      >
                        {"Log In"}
                      </div>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobile")
                        ? true
                        : true
                    ) ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xsUFj
                        )}
                      >
                        <button
                          className={classNames(
                            projectcss.all,
                            projectcss.button,
                            projectcss.__wab_text,
                            sty.button__pfqJi
                          )}
                        >
                          {"Start Free Trial"}
                        </button>
                      </div>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobile")
                        ? true
                        : true
                    ) ? (
                      <ChevronRightIcon
                        data-plasmic-name={"svg"}
                        data-plasmic-override={overrides.svg}
                        className={classNames(projectcss.all, sty.svg)}
                        role={"img"}
                      />
                    ) : null}
                  </div>
                ) : null}
              </div>
            </div>

            {(hasVariant(globalVariants, "screen", "mobile") ? true : true) ? (
              <div className={classNames(projectcss.all, sty.freeBox__tgOne)}>
                <div className={classNames(projectcss.all, sty.columns__lFpEn)}>
                  <div className={classNames(projectcss.all, sty.column__lHAm)}>
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__tQxJv)}
                      displayHeight={"80px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"144px" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/www_presell_ai/images/teluguIndiaNewDelhiJulianYu640806Unsplashjpg.jpeg",
                        fullWidth: 1960,
                        fullHeight: 1306,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__jVcz6)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gbqOb
                      )}
                    >
                      {"1-888-475-4473"}
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__tmw3)}>
            <div className={classNames(projectcss.all, sty.freeBox__lvjS)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wD9Au
                )}
              >
                {hasVariant(globalVariants, "screen", "mobile")
                  ? "FIELD SERVICE MANAGEMENT SOFTWARE"
                  : "FIELD SERVICE MANAGEMENT SOFTWARE"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4TDc4
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#75D718" }}
                  >
                    {"ORGANIZE "}
                  </span>
                  <React.Fragment>
                    {"YOUR FIELD\n SERVICE BUSINESS"}
                  </React.Fragment>
                </React.Fragment>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__k6Ti7)}>
                <form
                  data-plasmic-name={"form"}
                  data-plasmic-override={overrides.form}
                  className={classNames(projectcss.all, sty.form)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kLvcv
                    )}
                  >
                    {"TRY JOBBER FREE"}
                  </div>

                  <TextInput
                    className={classNames(
                      "__wab_instance",
                      sty.textInput__jaPvp
                    )}
                    placeholder={"Work Email" as const}
                  />

                  <TextInput
                    className={classNames(
                      "__wab_instance",
                      sty.textInput__oDgFb
                    )}
                    placeholder={"Add a Password" as const}
                  />

                  <button
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      projectcss.__wab_text,
                      sty.button__pJtrq
                    )}
                  >
                    {"START FREE TRIAL"}
                  </button>
                </form>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fv07C
                  )}
                >
                  {"Access all features. No credit card required"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dcJxs
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {
                        "By clicking “Start Free Trial” you agree to receive information from Jobber about our services, plus news and offers.\n You can unsubscribe at any time. You also agree to our "
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{
                        color: "#4178DF",
                        textDecorationLine: "underline"
                      }}
                    >
                      {"Terms of Service"}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#92B0EE" }}
                    >
                      {" "}
                    </span>
                    <React.Fragment>{"and "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{
                        color: "#4C8FDE",
                        textDecorationLine: "underline"
                      }}
                    >
                      {"Privacy Policy"}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#4C8FDE" }}
                    >
                      {"."}
                    </span>
                  </React.Fragment>
                </div>
              </div>
            </div>
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__kkZdX
            )}
          >
            {
              "Rated #1 most affordable and popular by thousands of service pros"
            }
          </div>

          {(hasVariant(globalVariants, "screen", "mobile") ? true : true) ? (
            <div className={classNames(projectcss.all, sty.freeBox__bEQzM)}>
              {(
                hasVariant(globalVariants, "screen", "mobile") ? true : true
              ) ? (
                <div
                  className={classNames(projectcss.all, sty.columns___3ZAxd)}
                >
                  {(
                    hasVariant(globalVariants, "screen", "mobile") ? true : true
                  ) ? (
                    <div
                      className={classNames(projectcss.all, sty.column__qbqwp)}
                    />
                  ) : null}
                </div>
              ) : null}
            </div>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : true) ? (
            <div className={classNames(projectcss.all, sty.columns__m3VUr)}>
              {(
                hasVariant(globalVariants, "screen", "mobile") ? true : true
              ) ? (
                <div className={classNames(projectcss.all, sty.column__uiOeL)}>
                  <div
                    className={classNames(projectcss.all, sty.columns__etfCh)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__vHCd)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__bTa8C)}
                        displayHeight={"42px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"103.62px" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/www_presell_ai/images/logoSliderMaidMentorpngpng.png",
                          fullWidth: 105,
                          fullHeight: 44,
                          aspectRatio: undefined
                        }}
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__oJNb8)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__mb4Lr)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"103.62px" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/www_presell_ai/images/logoSliderLawncarlifepngpng.png",
                          fullWidth: 105,
                          fullHeight: 54,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </div>
                </div>
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobile") ? true : true
              ) ? (
                <div className={classNames(projectcss.all, sty.column___97V4B)}>
                  <div
                    className={classNames(projectcss.all, sty.columns__zeHrb)}
                  >
                    {(
                      hasVariant(globalVariants, "screen", "mobile")
                        ? true
                        : true
                    ) ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___2Sggl
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__y6Z1A)}
                          displayHeight={"100%" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"103.62px" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/www_presell_ai/images/logoSliderDmupngpng.png",
                            fullWidth: 105,
                            fullHeight: 104,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}

                    <div
                      className={classNames(projectcss.all, sty.column__eBxJs)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__u13O)}
                        displayHeight={"42px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"103.62px" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/www_presell_ai/images/logoSliderBrolawspngpng.png",
                          fullWidth: 105,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </div>
                </div>
              ) : null}
            </div>
          ) : null}
          {(hasVariant(globalVariants, "screen", "mobile") ? true : true) ? (
            <div className={classNames(projectcss.all, sty.freeBox__wUzuY)}>
              <div className={classNames(projectcss.all, sty.columns___4P50V)}>
                {(
                  hasVariant(globalVariants, "screen", "mobile") ? true : true
                ) ? (
                  <div
                    className={classNames(projectcss.all, sty.column__p90Wp)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__haOts)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"180px" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/www_presell_ai/images/logoSliderMaidMentorpngpng.png",
                        fullWidth: 105,
                        fullHeight: 44,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobile") ? true : true
                ) ? (
                  <div
                    className={classNames(projectcss.all, sty.column__q1ZrL)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__fn1RK)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"180px" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/www_presell_ai/images/logoSliderLawncarlifepngpng.png",
                        fullWidth: 105,
                        fullHeight: 54,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                ) : null}
              </div>

              {(
                hasVariant(globalVariants, "screen", "mobile") ? true : true
              ) ? (
                <div className={classNames(projectcss.all, sty.freeBox___77Ke)}>
                  <div
                    className={classNames(projectcss.all, sty.columns__fkXzg)}
                  >
                    {(
                      hasVariant(globalVariants, "screen", "mobile")
                        ? true
                        : true
                    ) ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__uIvsc
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__g6TTx)}
                          displayHeight={"auto" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"180px" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/www_presell_ai/images/logoSliderDmupngpng.png",
                            fullWidth: 105,
                            fullHeight: 104,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobile")
                        ? true
                        : true
                    ) ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__qPi27
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___6K47F)}
                          displayHeight={"74px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"200px" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/www_presell_ai/images/logoSliderBrolawspngpng.png",
                            fullWidth: 105,
                            fullHeight: 36,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                  </div>
                </div>
              ) : null}
            </div>
          ) : null}

          <div className={classNames(projectcss.all, sty.freeBox__ciooW)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___1WkYk)}
              displayHeight={"61px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={
                hasVariant(globalVariants, "screen", "mobile")
                  ? ("650px" as const)
                  : ("600px" as const)
              }
              loading={"lazy" as const}
              src={{
                src: "/plasmic/www_presell_ai/images/divpng.png",
                fullWidth: 593,
                fullHeight: 62,
                aspectRatio: undefined
              }}
            />
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__ydyWw
            )}
          >
            {
              "Our features help you organize, manage, and grow your business:\n"
            }
          </div>

          {(hasVariant(globalVariants, "screen", "mobile") ? true : true) ? (
            <div className={classNames(projectcss.all, sty.freeBox__jr5Td)} />
          ) : null}

          <div className={classNames(projectcss.all, sty.freeBox__xwIrV)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__iO4De)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"20px" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/www_presell_ai/images/vectorpng.png",
                fullWidth: 16,
                fullHeight: 13,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__n4SDo
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Deliver a great customer experience"}
                </span>
                <React.Fragment>
                  {
                    " with Jobber’s client hub, branded customer communications, customized and automated emails and/or text messages, and custom checklists."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__tho2F)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__hbgmm)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"20px" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/www_presell_ai/images/vectorpng.png",
                fullWidth: 16,
                fullHeight: 13,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___1HUvf
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#000000", fontWeight: 700 }}
                >
                  {"Attract new customers"}
                </span>
                <React.Fragment>
                  {
                    " by allowing new leads to book through your website or Facebook page."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox___8Dxx3)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__x5NQq)}
              displayHeight={
                hasVariant(globalVariants, "screen", "mobile")
                  ? ("29px" as const)
                  : ("auto" as const)
              }
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"20px" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/www_presell_ai/images/vectorpng.png",
                fullWidth: 16,
                fullHeight: 13,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__oRvVd
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Send professional looking invoices"}
                </span>
                <React.Fragment>
                  {
                    " right from the mobile app. Customize your invoices by adding your branding and send with one-click when the job is done."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__uUM2)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__zBk2Q)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"20px" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/www_presell_ai/images/vectorpng.png",
                fullWidth: 16,
                fullHeight: 13,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ioEbm
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"Manage cash flow and get paid faster"}
                </span>
                <React.Fragment>
                  {
                    " with our invoicing and payment features. Batch invoicing, automated follow-ups that remind clients their invoice is due, and an easy, one-click option to pay by credit card online. Jobber also syncs with QuickBooks Online."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__gAIb6)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__fryIu)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"20px" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/www_presell_ai/images/vectorpng.png",
                fullWidth: 16,
                fullHeight: 13,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mPyhZ
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {
                    "Capture all client information in one place while on the go"
                  }
                </span>
                <React.Fragment>
                  {
                    ", with full client history, job and customer information, job details, checklists, notes, time tracking, and GPS directions."
                  }
                </React.Fragment>
              </React.Fragment>
            </div>
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__g9Yvy
            )}
          >
            {hasVariant(globalVariants, "screen", "mobile") ? (
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontStyle: "italic" }}
                >
                  {
                    "“Field service software allows you to focus on running the business, so the workweek isn’t running you.”"
                  }
                </span>
              </React.Fragment>
            ) : (
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontStyle: "italic" }}
                >
                  {
                    "“Field service software allows you to focus on running the business, so the"
                  }
                </span>
                <React.Fragment>{"\n"}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontStyle: "italic" }}
                >
                  {" workweek isn’t running you.”"}
                </span>
              </React.Fragment>
            )}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__zHIr
            )}
          >
            {hasVariant(globalVariants, "screen", "mobile")
              ? "-Ryaan Tuttle, Best Handyman Boston"
              : "-Ryaan Tuttle, Best Handyman Boston"}
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg", "form"],
  svg: ["svg"],
  form: ["form"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
  form: "form";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSignUpV2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSignUpV2__VariantsArgs;
    args?: PlasmicSignUpV2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSignUpV2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSignUpV2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSignUpV2__ArgProps,
          internalVariantPropNames: PlasmicSignUpV2__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicSignUpV2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSignUpV2";
  } else {
    func.displayName = `PlasmicSignUpV2.${nodeName}`;
  }
  return func;
}

export const PlasmicSignUpV2 = Object.assign(
  // Top-level PlasmicSignUpV2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    form: makeNodeComponent("form"),

    // Metadata about props expected for PlasmicSignUpV2
    internalVariantProps: PlasmicSignUpV2__VariantProps,
    internalArgProps: PlasmicSignUpV2__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Signup ",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSignUpV2;
/* prettier-ignore-end */
