// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hgYa2chxELsjCrsDiarb3T
// Component: 9_IECfX9BI
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_www_presell_ai.module.css"; // plasmic-import: hgYa2chxELsjCrsDiarb3T/projectcss
import sty from "./PlasmicSignUpV2FigmaImport.module.css"; // plasmic-import: 9_IECfX9BI/css

import IconLoginee285B38SvgIcon from "./icons/PlasmicIcon__IconLoginee285B38Svg"; // plasmic-import: Vd2UJLj9_L/icon
import FrameIcon from "./icons/PlasmicIcon__Frame"; // plasmic-import: mQdnen5etH/icon
import Frame2Icon from "./icons/PlasmicIcon__Frame2"; // plasmic-import: Lm4kpSt2fl/icon
import Frame3Icon from "./icons/PlasmicIcon__Frame3"; // plasmic-import: mC7EQz8zyM/icon
import Group3Icon from "./icons/PlasmicIcon__Group3"; // plasmic-import: 38bLqC9JJ8/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: _-HsDsjJcs/icon

export type PlasmicSignUpV2FigmaImport__VariantMembers = {};
export type PlasmicSignUpV2FigmaImport__VariantsArgs = {};
type VariantPropType = keyof PlasmicSignUpV2FigmaImport__VariantsArgs;
export const PlasmicSignUpV2FigmaImport__VariantProps =
  new Array<VariantPropType>();

export type PlasmicSignUpV2FigmaImport__ArgsType = {};
type ArgPropType = keyof PlasmicSignUpV2FigmaImport__ArgsType;
export const PlasmicSignUpV2FigmaImport__ArgProps = new Array<ArgPropType>();

export type PlasmicSignUpV2FigmaImport__OverridesType = {
  root?: p.Flex<"div">;
  getjobbercomByHtmltodesignFreeVersion04022023234100Gmt5?: p.Flex<"div">;
  body?: p.Flex<"div">;
  loginNavBar?: p.Flex<"div">;
  div2?: p.Flex<"div">;
  a?: p.Flex<"div">;
  aafter?: p.Flex<"div">;
  div3?: p.Flex<"div">;
  call?: p.Flex<"div">;
  frame?: p.Flex<"div">;
  a2?: p.Flex<"div">;
  svg2?: p.Flex<"div">;
  frame2?: p.Flex<"div">;
  a3?: p.Flex<"div">;
  divafter?: p.Flex<"div">;
  main?: p.Flex<"div">;
  article?: p.Flex<"div">;
  section?: p.Flex<"div">;
  div5?: p.Flex<"div">;
  div6?: p.Flex<"div">;
  form?: p.Flex<"div">;
  ul?: p.Flex<"div">;
  li?: p.Flex<"div">;
  inputemail?: p.Flex<"div">;
  workEmail?: p.Flex<"div">;
  li2?: p.Flex<"div">;
  inputpassword?: p.Flex<"div">;
  addAPassword?: p.Flex<"div">;
  div7?: p.Flex<"div">;
  button?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  buttonafter?: p.Flex<"div">;
  div8?: p.Flex<"div">;
  div9?: p.Flex<"div">;
  div10?: p.Flex<"div">;
  logoSliderMaidMentorpng?: p.Flex<"div">;
  logoSliderLawncarlifepng?: p.Flex<"div">;
  logoSliderDmupng?: p.Flex<"div">;
  logoSliderBrolawspng?: p.Flex<"div">;
  div11?: p.Flex<"div">;
  div12?: p.Flex<"div">;
  _5StarsOutOf5?: p.Flex<"div">;
  svg3?: p.Flex<"div">;
  svg4?: p.Flex<"div">;
  svg5?: p.Flex<"div">;
  svg6?: p.Flex<"div">;
  svg7?: p.Flex<"div">;
  capterra?: p.Flex<"div">;
  frame3?: p.Flex<"div">;
  hpDesignRevised?: p.Flex<"div">;
  hpDesktop?: p.Flex<"div">;
  starRating?: p.Flex<"div">;
  div13?: p.Flex<"div">;
  _45StarsOutOf5?: p.Flex<"div">;
  svg8?: p.Flex<"div">;
  svg9?: p.Flex<"div">;
  svg10?: p.Flex<"div">;
  svg11?: p.Flex<"div">;
  svg12?: p.Flex<"div">;
  softwareAdvice?: p.Flex<"div">;
  frame4?: p.Flex<"div">;
  div14?: p.Flex<"div">;
  _45StarsOutOf6?: p.Flex<"div">;
  svg13?: p.Flex<"div">;
  svg14?: p.Flex<"div">;
  svg15?: p.Flex<"div">;
  svg16?: p.Flex<"div">;
  svg17?: p.Flex<"div">;
  quickBooks?: p.Flex<"div">;
  frame5?: p.Flex<"div">;
  div15?: p.Flex<"div">;
  _5StarsOutOf6?: p.Flex<"div">;
  svg18?: p.Flex<"div">;
  svg19?: p.Flex<"div">;
  svg20?: p.Flex<"div">;
  svg21?: p.Flex<"div">;
  svg22?: p.Flex<"div">;
  facebook?: p.Flex<"div">;
  frame6?: p.Flex<"div">;
  group?: p.Flex<"div">;
  div16?: p.Flex<"div">;
  ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness?: p.Flex<"div">;
  ul2?: p.Flex<"div">;
  li3?: p.Flex<"div">;
  i?: p.Flex<"div">;
  iconCheckmark1Be90Bf8Svg?: p.Flex<"div">;
  symbols?: p.Flex<"div">;
  iconSuccess?: p.Flex<"div">;
  li4?: p.Flex<"div">;
  i2?: p.Flex<"div">;
  iconCheckmark1Be90Bf8Svg2?: p.Flex<"div">;
  symbols2?: p.Flex<"div">;
  iconSuccess2?: p.Flex<"div">;
  li5?: p.Flex<"div">;
  i3?: p.Flex<"div">;
  iconCheckmark1Be90Bf8Svg3?: p.Flex<"div">;
  symbols3?: p.Flex<"div">;
  iconSuccess3?: p.Flex<"div">;
  li6?: p.Flex<"div">;
  i4?: p.Flex<"div">;
  iconCheckmark1Be90Bf8Svg4?: p.Flex<"div">;
  symbols4?: p.Flex<"div">;
  iconSuccess4?: p.Flex<"div">;
  li7?: p.Flex<"div">;
  i5?: p.Flex<"div">;
  iconCheckmark1Be90Bf8Svg5?: p.Flex<"div">;
  symbols5?: p.Flex<"div">;
  iconSuccess5?: p.Flex<"div">;
};

export interface DefaultSignUpV2FigmaImportProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicSignUpV2FigmaImport__RenderFunc(props: {
  variants: PlasmicSignUpV2FigmaImport__VariantsArgs;
  args: PlasmicSignUpV2FigmaImport__ArgsType;
  overrides: PlasmicSignUpV2FigmaImport__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={
              "getjobbercomByHtmltodesignFreeVersion04022023234100Gmt5"
            }
            data-plasmic-override={
              overrides.getjobbercomByHtmltodesignFreeVersion04022023234100Gmt5
            }
            className={classNames(
              projectcss.all,
              sty.getjobbercomByHtmltodesignFreeVersion04022023234100Gmt5
            )}
          >
            <div
              data-plasmic-name={"body"}
              data-plasmic-override={overrides.body}
              className={classNames(projectcss.all, sty.body)}
            >
              <div
                data-plasmic-name={"loginNavBar"}
                data-plasmic-override={overrides.loginNavBar}
                className={classNames(projectcss.all, sty.loginNavBar)}
              >
                <div
                  data-plasmic-name={"div2"}
                  data-plasmic-override={overrides.div2}
                  className={classNames(projectcss.all, sty.div2)}
                >
                  <div
                    data-plasmic-name={"a"}
                    data-plasmic-override={overrides.a}
                    className={classNames(projectcss.all, sty.a)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lr8V4
                      )}
                    >
                      {"Log In"}
                    </div>

                    <div
                      data-plasmic-name={"aafter"}
                      data-plasmic-override={overrides.aafter}
                      className={classNames(projectcss.all, sty.aafter)}
                    >
                      <IconLoginee285B38SvgIcon
                        className={classNames(projectcss.all, sty.svg__z2QO)}
                        role={"img"}
                      />
                    </div>
                  </div>
                </div>
              </div>

              <div
                data-plasmic-name={"div3"}
                data-plasmic-override={overrides.div3}
                className={classNames(projectcss.all, sty.div3)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"call"}
                  data-plasmic-override={overrides.call}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.call)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__pdlO9)}
                  >
                    <div
                      data-plasmic-name={"frame"}
                      data-plasmic-override={overrides.frame}
                      className={classNames(projectcss.all, sty.frame)}
                    />
                  </div>

                  <div
                    data-plasmic-name={"a2"}
                    data-plasmic-override={overrides.a2}
                    className={classNames(projectcss.all, sty.a2)}
                  >
                    <div
                      data-plasmic-name={"svg2"}
                      data-plasmic-override={overrides.svg2}
                      className={classNames(projectcss.all, sty.svg2)}
                    >
                      <div
                        data-plasmic-name={"frame2"}
                        data-plasmic-override={overrides.frame2}
                        className={classNames(projectcss.all, sty.frame2)}
                      />
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wwMod
                      )}
                    >
                      {"1-888-475-4473"}
                    </div>
                  </div>
                </p.Stack>

                <div
                  data-plasmic-name={"a3"}
                  data-plasmic-override={overrides.a3}
                  className={classNames(projectcss.all, sty.a3)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zWf99
                    )}
                  >
                    {"Skip to content"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"divafter"}
                  data-plasmic-override={overrides.divafter}
                  className={classNames(projectcss.all, sty.divafter)}
                />
              </div>

              <div
                data-plasmic-name={"main"}
                data-plasmic-override={overrides.main}
                className={classNames(projectcss.all, sty.main)}
              >
                <div
                  data-plasmic-name={"article"}
                  data-plasmic-override={overrides.article}
                  className={classNames(projectcss.all, sty.article)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"section"}
                    data-plasmic-override={overrides.section}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.section)}
                  >
                    <div
                      data-plasmic-name={"div5"}
                      data-plasmic-override={overrides.div5}
                      className={classNames(projectcss.all, sty.div5)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bd8QC
                        )}
                      >
                        {"Field Service Management Software"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___17TE
                        )}
                      >
                        {"Organize your field\n service business"}
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"div6"}
                      data-plasmic-override={overrides.div6}
                      className={classNames(projectcss.all, sty.div6)}
                    >
                      <div
                        data-plasmic-name={"form"}
                        data-plasmic-override={overrides.form}
                        className={classNames(projectcss.all, sty.form)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__drrI5
                          )}
                        >
                          {"TRY JOBBER FREE"}
                        </div>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"ul"}
                          data-plasmic-override={overrides.ul}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.ul)}
                        >
                          <div
                            data-plasmic-name={"li"}
                            data-plasmic-override={overrides.li}
                            className={classNames(projectcss.all, sty.li)}
                          >
                            <div
                              data-plasmic-name={"inputemail"}
                              data-plasmic-override={overrides.inputemail}
                              className={classNames(
                                projectcss.all,
                                sty.inputemail
                              )}
                            />

                            <div
                              data-plasmic-name={"workEmail"}
                              data-plasmic-override={overrides.workEmail}
                              className={classNames(
                                projectcss.all,
                                sty.workEmail
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__qt3Rw
                                )}
                              >
                                {"Work Email"}
                              </div>
                            </div>
                          </div>

                          <div
                            data-plasmic-name={"li2"}
                            data-plasmic-override={overrides.li2}
                            className={classNames(projectcss.all, sty.li2)}
                          >
                            <div
                              data-plasmic-name={"inputpassword"}
                              data-plasmic-override={overrides.inputpassword}
                              className={classNames(
                                projectcss.all,
                                sty.inputpassword
                              )}
                            />

                            <div
                              data-plasmic-name={"addAPassword"}
                              data-plasmic-override={overrides.addAPassword}
                              className={classNames(
                                projectcss.all,
                                sty.addAPassword
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__vahab
                                )}
                              >
                                {"Add a Password"}
                              </div>
                            </div>
                          </div>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"div7"}
                          data-plasmic-override={overrides.div7}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.div7)}
                        >
                          <div
                            data-plasmic-name={"button"}
                            data-plasmic-override={overrides.button}
                            className={classNames(projectcss.all, sty.button)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__szNbh
                              )}
                            >
                              {"Start Free Trial"}
                            </div>

                            <div
                              data-plasmic-name={"freeBox"}
                              data-plasmic-override={overrides.freeBox}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox
                              )}
                            >
                              <div
                                data-plasmic-name={"buttonafter"}
                                data-plasmic-override={overrides.buttonafter}
                                className={classNames(
                                  projectcss.all,
                                  sty.buttonafter
                                )}
                              />
                            </div>
                          </div>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"div8"}
                            data-plasmic-override={overrides.div8}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.div8)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__xFqB7
                              )}
                            >
                              {"Access all features. No credit card required"}
                            </div>

                            <div
                              data-plasmic-name={"div9"}
                              data-plasmic-override={overrides.div9}
                              className={classNames(projectcss.all, sty.div9)}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__oH31B
                                )}
                              >
                                {
                                  "By clicking “Start Free Trial” you agree to receive information from Jobber about our services, plus news and offers.\n You can unsubscribe at any time. You also agree to our Terms of Service and Privacy Policy."
                                }
                              </div>
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>

                      <div
                        data-plasmic-name={"div10"}
                        data-plasmic-override={overrides.div10}
                        className={classNames(projectcss.all, sty.div10)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__heCfB
                          )}
                        >
                          {
                            "Rated #1 most affordable and popular by thousands of service pros"
                          }
                        </div>

                        <div
                          data-plasmic-name={"logoSliderMaidMentorpng"}
                          data-plasmic-override={
                            overrides.logoSliderMaidMentorpng
                          }
                          className={classNames(
                            projectcss.all,
                            sty.logoSliderMaidMentorpng
                          )}
                        />

                        <div
                          data-plasmic-name={"logoSliderLawncarlifepng"}
                          data-plasmic-override={
                            overrides.logoSliderLawncarlifepng
                          }
                          className={classNames(
                            projectcss.all,
                            sty.logoSliderLawncarlifepng
                          )}
                        />

                        <div
                          data-plasmic-name={"logoSliderDmupng"}
                          data-plasmic-override={overrides.logoSliderDmupng}
                          className={classNames(
                            projectcss.all,
                            sty.logoSliderDmupng
                          )}
                        />

                        <div
                          data-plasmic-name={"logoSliderBrolawspng"}
                          data-plasmic-override={overrides.logoSliderBrolawspng}
                          className={classNames(
                            projectcss.all,
                            sty.logoSliderBrolawspng
                          )}
                        />
                      </div>

                      <div
                        data-plasmic-name={"div11"}
                        data-plasmic-override={overrides.div11}
                        className={classNames(projectcss.all, sty.div11)}
                      >
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"div12"}
                          data-plasmic-override={overrides.div12}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.div12)}
                        >
                          <div
                            data-plasmic-name={"_5StarsOutOf5"}
                            data-plasmic-override={overrides._5StarsOutOf5}
                            className={classNames(
                              projectcss.all,
                              sty._5StarsOutOf5
                            )}
                          >
                            <div
                              data-plasmic-name={"svg3"}
                              data-plasmic-override={overrides.svg3}
                              className={classNames(projectcss.all, sty.svg3)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__f2Ns4
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg4"}
                              data-plasmic-override={overrides.svg4}
                              className={classNames(projectcss.all, sty.svg4)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__t1KHw
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg5"}
                              data-plasmic-override={overrides.svg5}
                              className={classNames(projectcss.all, sty.svg5)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__uMRs
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg6"}
                              data-plasmic-override={overrides.svg6}
                              className={classNames(projectcss.all, sty.svg6)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__bGl5M
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg7"}
                              data-plasmic-override={overrides.svg7}
                              className={classNames(projectcss.all, sty.svg7)}
                            >
                              <Frame2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__kbWvu
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>

                          <div
                            data-plasmic-name={"capterra"}
                            data-plasmic-override={overrides.capterra}
                            className={classNames(projectcss.all, sty.capterra)}
                          >
                            <div
                              data-plasmic-name={"frame3"}
                              data-plasmic-override={overrides.frame3}
                              className={classNames(projectcss.all, sty.frame3)}
                            >
                              <div
                                data-plasmic-name={"hpDesignRevised"}
                                data-plasmic-override={
                                  overrides.hpDesignRevised
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.hpDesignRevised
                                )}
                              >
                                <div
                                  data-plasmic-name={"hpDesktop"}
                                  data-plasmic-override={overrides.hpDesktop}
                                  className={classNames(
                                    projectcss.all,
                                    sty.hpDesktop
                                  )}
                                >
                                  <div
                                    data-plasmic-name={"starRating"}
                                    data-plasmic-override={overrides.starRating}
                                    className={classNames(
                                      projectcss.all,
                                      sty.starRating
                                    )}
                                  >
                                    <p.PlasmicImg
                                      alt={""}
                                      className={classNames(sty.img__xntXn)}
                                      displayHeight={"12.857px" as const}
                                      displayMaxHeight={"none" as const}
                                      displayMaxWidth={"100%" as const}
                                      displayMinHeight={"0" as const}
                                      displayMinWidth={"0" as const}
                                      displayWidth={"58.232px" as const}
                                      loading={"lazy" as const}
                                      src={{
                                        src: "/plasmic/www_presell_ai/images/capterraLogo.svg",
                                        fullWidth: 58.232,
                                        fullHeight: 12.857,
                                        aspectRatio: 4.538462
                                      }}
                                    />
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"div13"}
                          data-plasmic-override={overrides.div13}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.div13)}
                        >
                          <div
                            data-plasmic-name={"_45StarsOutOf5"}
                            data-plasmic-override={overrides._45StarsOutOf5}
                            className={classNames(
                              projectcss.all,
                              sty._45StarsOutOf5
                            )}
                          >
                            <div
                              data-plasmic-name={"svg8"}
                              data-plasmic-override={overrides.svg8}
                              className={classNames(projectcss.all, sty.svg8)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__mAcy5
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg9"}
                              data-plasmic-override={overrides.svg9}
                              className={classNames(projectcss.all, sty.svg9)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__rf5FE
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg10"}
                              data-plasmic-override={overrides.svg10}
                              className={classNames(projectcss.all, sty.svg10)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__lOpMn
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg11"}
                              data-plasmic-override={overrides.svg11}
                              className={classNames(projectcss.all, sty.svg11)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__jvF3N
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg12"}
                              data-plasmic-override={overrides.svg12}
                              className={classNames(projectcss.all, sty.svg12)}
                            >
                              <Frame3Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___61OBb
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>

                          <div
                            data-plasmic-name={"softwareAdvice"}
                            data-plasmic-override={overrides.softwareAdvice}
                            className={classNames(
                              projectcss.all,
                              sty.softwareAdvice
                            )}
                          >
                            <div
                              data-plasmic-name={"frame4"}
                              data-plasmic-override={overrides.frame4}
                              className={classNames(projectcss.all, sty.frame4)}
                            >
                              <p.PlasmicImg
                                alt={""}
                                className={classNames(sty.img__hRqRv)}
                                displayHeight={"12.902px" as const}
                                displayMaxHeight={"none" as const}
                                displayMaxWidth={"100%" as const}
                                displayMinHeight={"0" as const}
                                displayMinWidth={"0" as const}
                                displayWidth={"117.669px" as const}
                                loading={"lazy" as const}
                                src={{
                                  src: "/plasmic/www_presell_ai/images/group.svg",
                                  fullWidth: 117.669,
                                  fullHeight: 12.902,
                                  aspectRatio: 9.076923
                                }}
                              />
                            </div>
                          </div>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"div14"}
                          data-plasmic-override={overrides.div14}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.div14)}
                        >
                          <div
                            data-plasmic-name={"_45StarsOutOf6"}
                            data-plasmic-override={overrides._45StarsOutOf6}
                            className={classNames(
                              projectcss.all,
                              sty._45StarsOutOf6
                            )}
                          >
                            <div
                              data-plasmic-name={"svg13"}
                              data-plasmic-override={overrides.svg13}
                              className={classNames(projectcss.all, sty.svg13)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ihZ7M
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg14"}
                              data-plasmic-override={overrides.svg14}
                              className={classNames(projectcss.all, sty.svg14)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__xJ9X
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg15"}
                              data-plasmic-override={overrides.svg15}
                              className={classNames(projectcss.all, sty.svg15)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ik54V
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg16"}
                              data-plasmic-override={overrides.svg16}
                              className={classNames(projectcss.all, sty.svg16)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ufMuw
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg17"}
                              data-plasmic-override={overrides.svg17}
                              className={classNames(projectcss.all, sty.svg17)}
                            >
                              <Frame3Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___7D3Iv
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>

                          <div
                            data-plasmic-name={"quickBooks"}
                            data-plasmic-override={overrides.quickBooks}
                            className={classNames(
                              projectcss.all,
                              sty.quickBooks
                            )}
                          >
                            <div
                              data-plasmic-name={"frame5"}
                              data-plasmic-override={overrides.frame5}
                              className={classNames(projectcss.all, sty.frame5)}
                            >
                              <p.PlasmicImg
                                alt={""}
                                className={classNames(sty.img__iptm5)}
                                displayHeight={"12.942px" as const}
                                displayMaxHeight={"none" as const}
                                displayMaxWidth={"100%" as const}
                                displayMinHeight={"0" as const}
                                displayMinWidth={"0" as const}
                                displayWidth={"67.581px" as const}
                                loading={"lazy" as const}
                                src={{
                                  src: "/plasmic/www_presell_ai/images/group2.svg",
                                  fullWidth: 67.581,
                                  fullHeight: 12.942,
                                  aspectRatio: 5.230769
                                }}
                              />
                            </div>
                          </div>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"div15"}
                          data-plasmic-override={overrides.div15}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.div15)}
                        >
                          <div
                            data-plasmic-name={"_5StarsOutOf6"}
                            data-plasmic-override={overrides._5StarsOutOf6}
                            className={classNames(
                              projectcss.all,
                              sty._5StarsOutOf6
                            )}
                          >
                            <div
                              data-plasmic-name={"svg18"}
                              data-plasmic-override={overrides.svg18}
                              className={classNames(projectcss.all, sty.svg18)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__gcXrn
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg19"}
                              data-plasmic-override={overrides.svg19}
                              className={classNames(projectcss.all, sty.svg19)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__mGtOk
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg20"}
                              data-plasmic-override={overrides.svg20}
                              className={classNames(projectcss.all, sty.svg20)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__nBtB
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg21"}
                              data-plasmic-override={overrides.svg21}
                              className={classNames(projectcss.all, sty.svg21)}
                            >
                              <FrameIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__bmKOg
                                )}
                                role={"img"}
                              />
                            </div>

                            <div
                              data-plasmic-name={"svg22"}
                              data-plasmic-override={overrides.svg22}
                              className={classNames(projectcss.all, sty.svg22)}
                            >
                              <Frame2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__nyWmH
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>

                          <div
                            data-plasmic-name={"facebook"}
                            data-plasmic-override={overrides.facebook}
                            className={classNames(projectcss.all, sty.facebook)}
                          >
                            <div
                              data-plasmic-name={"frame6"}
                              data-plasmic-override={overrides.frame6}
                              className={classNames(projectcss.all, sty.frame6)}
                            >
                              <div
                                data-plasmic-name={"group"}
                                data-plasmic-override={overrides.group}
                                className={classNames(
                                  projectcss.all,
                                  sty.group
                                )}
                              >
                                <Group3Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__sT59U
                                  )}
                                  role={"img"}
                                />
                              </div>
                            </div>
                          </div>
                        </p.Stack>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"div16"}
                      data-plasmic-override={overrides.div16}
                      className={classNames(projectcss.all, sty.div16)}
                    >
                      <div
                        data-plasmic-name={
                          "ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness"
                        }
                        data-plasmic-override={
                          overrides.ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness
                        }
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness
                        )}
                      >
                        {
                          "Our features help you organize, manage, and grow your business:\n"
                        }
                      </div>

                      <div
                        data-plasmic-name={"ul2"}
                        data-plasmic-override={overrides.ul2}
                        className={classNames(projectcss.all, sty.ul2)}
                      >
                        <div
                          data-plasmic-name={"li3"}
                          data-plasmic-override={overrides.li3}
                          className={classNames(projectcss.all, sty.li3)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___0TOul
                            )}
                          >
                            {
                              "Attract new customers by allowing new leads to book through your website or Facebook page."
                            }
                          </div>

                          <div
                            data-plasmic-name={"i"}
                            data-plasmic-override={overrides.i}
                            className={classNames(projectcss.all, sty.i)}
                          >
                            <div
                              data-plasmic-name={"iconCheckmark1Be90Bf8Svg"}
                              data-plasmic-override={
                                overrides.iconCheckmark1Be90Bf8Svg
                              }
                              className={classNames(
                                projectcss.all,
                                sty.iconCheckmark1Be90Bf8Svg
                              )}
                            >
                              <div
                                data-plasmic-name={"symbols"}
                                data-plasmic-override={overrides.symbols}
                                className={classNames(
                                  projectcss.all,
                                  sty.symbols
                                )}
                              >
                                <div
                                  data-plasmic-name={"iconSuccess"}
                                  data-plasmic-override={overrides.iconSuccess}
                                  className={classNames(
                                    projectcss.all,
                                    sty.iconSuccess
                                  )}
                                >
                                  <Icon3Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__asjA6
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>

                        <div
                          data-plasmic-name={"li4"}
                          data-plasmic-override={overrides.li4}
                          className={classNames(projectcss.all, sty.li4)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zVQsd
                            )}
                          >
                            {
                              "Send professional looking invoices right from the mobile app. Customize your invoices by adding your branding and send with one-click when the job is done."
                            }
                          </div>

                          <div
                            data-plasmic-name={"i2"}
                            data-plasmic-override={overrides.i2}
                            className={classNames(projectcss.all, sty.i2)}
                          >
                            <div
                              data-plasmic-name={"iconCheckmark1Be90Bf8Svg2"}
                              data-plasmic-override={
                                overrides.iconCheckmark1Be90Bf8Svg2
                              }
                              className={classNames(
                                projectcss.all,
                                sty.iconCheckmark1Be90Bf8Svg2
                              )}
                            >
                              <div
                                data-plasmic-name={"symbols2"}
                                data-plasmic-override={overrides.symbols2}
                                className={classNames(
                                  projectcss.all,
                                  sty.symbols2
                                )}
                              >
                                <div
                                  data-plasmic-name={"iconSuccess2"}
                                  data-plasmic-override={overrides.iconSuccess2}
                                  className={classNames(
                                    projectcss.all,
                                    sty.iconSuccess2
                                  )}
                                >
                                  <Icon3Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__nbXaV
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>

                        <div
                          data-plasmic-name={"li5"}
                          data-plasmic-override={overrides.li5}
                          className={classNames(projectcss.all, sty.li5)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ocEbs
                            )}
                          >
                            {
                              "Manage cash flow and get paid faster with our invoicing and payment features. Batch invoicing, automated follow-ups that remind clients their invoice is due, and an easy, one-click option to pay by credit card online. Jobber also syncs with QuickBooks Online."
                            }
                          </div>

                          <div
                            data-plasmic-name={"i3"}
                            data-plasmic-override={overrides.i3}
                            className={classNames(projectcss.all, sty.i3)}
                          >
                            <div
                              data-plasmic-name={"iconCheckmark1Be90Bf8Svg3"}
                              data-plasmic-override={
                                overrides.iconCheckmark1Be90Bf8Svg3
                              }
                              className={classNames(
                                projectcss.all,
                                sty.iconCheckmark1Be90Bf8Svg3
                              )}
                            >
                              <div
                                data-plasmic-name={"symbols3"}
                                data-plasmic-override={overrides.symbols3}
                                className={classNames(
                                  projectcss.all,
                                  sty.symbols3
                                )}
                              >
                                <div
                                  data-plasmic-name={"iconSuccess3"}
                                  data-plasmic-override={overrides.iconSuccess3}
                                  className={classNames(
                                    projectcss.all,
                                    sty.iconSuccess3
                                  )}
                                >
                                  <Icon3Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__pspJ4
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>

                        <div
                          data-plasmic-name={"li6"}
                          data-plasmic-override={overrides.li6}
                          className={classNames(projectcss.all, sty.li6)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bb7G
                            )}
                          >
                            {
                              "Deliver a great customer experience with Jobber’s client hub, branded customer communications, customized and automated emails and/or text messages, and custom checklists."
                            }
                          </div>

                          <div
                            data-plasmic-name={"i4"}
                            data-plasmic-override={overrides.i4}
                            className={classNames(projectcss.all, sty.i4)}
                          >
                            <div
                              data-plasmic-name={"iconCheckmark1Be90Bf8Svg4"}
                              data-plasmic-override={
                                overrides.iconCheckmark1Be90Bf8Svg4
                              }
                              className={classNames(
                                projectcss.all,
                                sty.iconCheckmark1Be90Bf8Svg4
                              )}
                            >
                              <div
                                data-plasmic-name={"symbols4"}
                                data-plasmic-override={overrides.symbols4}
                                className={classNames(
                                  projectcss.all,
                                  sty.symbols4
                                )}
                              >
                                <div
                                  data-plasmic-name={"iconSuccess4"}
                                  data-plasmic-override={overrides.iconSuccess4}
                                  className={classNames(
                                    projectcss.all,
                                    sty.iconSuccess4
                                  )}
                                >
                                  <Icon3Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg__wghI2
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>

                        <div
                          data-plasmic-name={"li7"}
                          data-plasmic-override={overrides.li7}
                          className={classNames(projectcss.all, sty.li7)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__e34O
                            )}
                          >
                            {
                              "Capture all client information in one place while on the go, with full client history, job and customer information, job details, checklists, notes, time tracking, and GPS directions."
                            }
                          </div>

                          <div
                            data-plasmic-name={"i5"}
                            data-plasmic-override={overrides.i5}
                            className={classNames(projectcss.all, sty.i5)}
                          >
                            <div
                              data-plasmic-name={"iconCheckmark1Be90Bf8Svg5"}
                              data-plasmic-override={
                                overrides.iconCheckmark1Be90Bf8Svg5
                              }
                              className={classNames(
                                projectcss.all,
                                sty.iconCheckmark1Be90Bf8Svg5
                              )}
                            >
                              <div
                                data-plasmic-name={"symbols5"}
                                data-plasmic-override={overrides.symbols5}
                                className={classNames(
                                  projectcss.all,
                                  sty.symbols5
                                )}
                              >
                                <div
                                  data-plasmic-name={"iconSuccess5"}
                                  data-plasmic-override={overrides.iconSuccess5}
                                  className={classNames(
                                    projectcss.all,
                                    sty.iconSuccess5
                                  )}
                                >
                                  <Icon3Icon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg___8HxaJ
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dfi39
                        )}
                      >
                        {
                          "“Field service software allows you to focus on running the business, so the workweek isn’t running you.”"
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gxOy8
                        )}
                      >
                        {"-Ryaan Tuttle, Best Handyman Boston"}
                      </div>
                    </div>
                  </p.Stack>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "getjobbercomByHtmltodesignFreeVersion04022023234100Gmt5",
    "body",
    "loginNavBar",
    "div2",
    "a",
    "aafter",
    "div3",
    "call",
    "frame",
    "a2",
    "svg2",
    "frame2",
    "a3",
    "divafter",
    "main",
    "article",
    "section",
    "div5",
    "div6",
    "form",
    "ul",
    "li",
    "inputemail",
    "workEmail",
    "li2",
    "inputpassword",
    "addAPassword",
    "div7",
    "button",
    "freeBox",
    "buttonafter",
    "div8",
    "div9",
    "div10",
    "logoSliderMaidMentorpng",
    "logoSliderLawncarlifepng",
    "logoSliderDmupng",
    "logoSliderBrolawspng",
    "div11",
    "div12",
    "_5StarsOutOf5",
    "svg3",
    "svg4",
    "svg5",
    "svg6",
    "svg7",
    "capterra",
    "frame3",
    "hpDesignRevised",
    "hpDesktop",
    "starRating",
    "div13",
    "_45StarsOutOf5",
    "svg8",
    "svg9",
    "svg10",
    "svg11",
    "svg12",
    "softwareAdvice",
    "frame4",
    "div14",
    "_45StarsOutOf6",
    "svg13",
    "svg14",
    "svg15",
    "svg16",
    "svg17",
    "quickBooks",
    "frame5",
    "div15",
    "_5StarsOutOf6",
    "svg18",
    "svg19",
    "svg20",
    "svg21",
    "svg22",
    "facebook",
    "frame6",
    "group",
    "div16",
    "ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness",
    "ul2",
    "li3",
    "i",
    "iconCheckmark1Be90Bf8Svg",
    "symbols",
    "iconSuccess",
    "li4",
    "i2",
    "iconCheckmark1Be90Bf8Svg2",
    "symbols2",
    "iconSuccess2",
    "li5",
    "i3",
    "iconCheckmark1Be90Bf8Svg3",
    "symbols3",
    "iconSuccess3",
    "li6",
    "i4",
    "iconCheckmark1Be90Bf8Svg4",
    "symbols4",
    "iconSuccess4",
    "li7",
    "i5",
    "iconCheckmark1Be90Bf8Svg5",
    "symbols5",
    "iconSuccess5"
  ],
  getjobbercomByHtmltodesignFreeVersion04022023234100Gmt5: [
    "getjobbercomByHtmltodesignFreeVersion04022023234100Gmt5",
    "body",
    "loginNavBar",
    "div2",
    "a",
    "aafter",
    "div3",
    "call",
    "frame",
    "a2",
    "svg2",
    "frame2",
    "a3",
    "divafter",
    "main",
    "article",
    "section",
    "div5",
    "div6",
    "form",
    "ul",
    "li",
    "inputemail",
    "workEmail",
    "li2",
    "inputpassword",
    "addAPassword",
    "div7",
    "button",
    "freeBox",
    "buttonafter",
    "div8",
    "div9",
    "div10",
    "logoSliderMaidMentorpng",
    "logoSliderLawncarlifepng",
    "logoSliderDmupng",
    "logoSliderBrolawspng",
    "div11",
    "div12",
    "_5StarsOutOf5",
    "svg3",
    "svg4",
    "svg5",
    "svg6",
    "svg7",
    "capterra",
    "frame3",
    "hpDesignRevised",
    "hpDesktop",
    "starRating",
    "div13",
    "_45StarsOutOf5",
    "svg8",
    "svg9",
    "svg10",
    "svg11",
    "svg12",
    "softwareAdvice",
    "frame4",
    "div14",
    "_45StarsOutOf6",
    "svg13",
    "svg14",
    "svg15",
    "svg16",
    "svg17",
    "quickBooks",
    "frame5",
    "div15",
    "_5StarsOutOf6",
    "svg18",
    "svg19",
    "svg20",
    "svg21",
    "svg22",
    "facebook",
    "frame6",
    "group",
    "div16",
    "ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness",
    "ul2",
    "li3",
    "i",
    "iconCheckmark1Be90Bf8Svg",
    "symbols",
    "iconSuccess",
    "li4",
    "i2",
    "iconCheckmark1Be90Bf8Svg2",
    "symbols2",
    "iconSuccess2",
    "li5",
    "i3",
    "iconCheckmark1Be90Bf8Svg3",
    "symbols3",
    "iconSuccess3",
    "li6",
    "i4",
    "iconCheckmark1Be90Bf8Svg4",
    "symbols4",
    "iconSuccess4",
    "li7",
    "i5",
    "iconCheckmark1Be90Bf8Svg5",
    "symbols5",
    "iconSuccess5"
  ],
  body: [
    "body",
    "loginNavBar",
    "div2",
    "a",
    "aafter",
    "div3",
    "call",
    "frame",
    "a2",
    "svg2",
    "frame2",
    "a3",
    "divafter",
    "main",
    "article",
    "section",
    "div5",
    "div6",
    "form",
    "ul",
    "li",
    "inputemail",
    "workEmail",
    "li2",
    "inputpassword",
    "addAPassword",
    "div7",
    "button",
    "freeBox",
    "buttonafter",
    "div8",
    "div9",
    "div10",
    "logoSliderMaidMentorpng",
    "logoSliderLawncarlifepng",
    "logoSliderDmupng",
    "logoSliderBrolawspng",
    "div11",
    "div12",
    "_5StarsOutOf5",
    "svg3",
    "svg4",
    "svg5",
    "svg6",
    "svg7",
    "capterra",
    "frame3",
    "hpDesignRevised",
    "hpDesktop",
    "starRating",
    "div13",
    "_45StarsOutOf5",
    "svg8",
    "svg9",
    "svg10",
    "svg11",
    "svg12",
    "softwareAdvice",
    "frame4",
    "div14",
    "_45StarsOutOf6",
    "svg13",
    "svg14",
    "svg15",
    "svg16",
    "svg17",
    "quickBooks",
    "frame5",
    "div15",
    "_5StarsOutOf6",
    "svg18",
    "svg19",
    "svg20",
    "svg21",
    "svg22",
    "facebook",
    "frame6",
    "group",
    "div16",
    "ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness",
    "ul2",
    "li3",
    "i",
    "iconCheckmark1Be90Bf8Svg",
    "symbols",
    "iconSuccess",
    "li4",
    "i2",
    "iconCheckmark1Be90Bf8Svg2",
    "symbols2",
    "iconSuccess2",
    "li5",
    "i3",
    "iconCheckmark1Be90Bf8Svg3",
    "symbols3",
    "iconSuccess3",
    "li6",
    "i4",
    "iconCheckmark1Be90Bf8Svg4",
    "symbols4",
    "iconSuccess4",
    "li7",
    "i5",
    "iconCheckmark1Be90Bf8Svg5",
    "symbols5",
    "iconSuccess5"
  ],
  loginNavBar: ["loginNavBar", "div2", "a", "aafter"],
  div2: ["div2", "a", "aafter"],
  a: ["a", "aafter"],
  aafter: ["aafter"],
  div3: ["div3", "call", "frame", "a2", "svg2", "frame2", "a3", "divafter"],
  call: ["call", "frame", "a2", "svg2", "frame2"],
  frame: ["frame"],
  a2: ["a2", "svg2", "frame2"],
  svg2: ["svg2", "frame2"],
  frame2: ["frame2"],
  a3: ["a3"],
  divafter: ["divafter"],
  main: [
    "main",
    "article",
    "section",
    "div5",
    "div6",
    "form",
    "ul",
    "li",
    "inputemail",
    "workEmail",
    "li2",
    "inputpassword",
    "addAPassword",
    "div7",
    "button",
    "freeBox",
    "buttonafter",
    "div8",
    "div9",
    "div10",
    "logoSliderMaidMentorpng",
    "logoSliderLawncarlifepng",
    "logoSliderDmupng",
    "logoSliderBrolawspng",
    "div11",
    "div12",
    "_5StarsOutOf5",
    "svg3",
    "svg4",
    "svg5",
    "svg6",
    "svg7",
    "capterra",
    "frame3",
    "hpDesignRevised",
    "hpDesktop",
    "starRating",
    "div13",
    "_45StarsOutOf5",
    "svg8",
    "svg9",
    "svg10",
    "svg11",
    "svg12",
    "softwareAdvice",
    "frame4",
    "div14",
    "_45StarsOutOf6",
    "svg13",
    "svg14",
    "svg15",
    "svg16",
    "svg17",
    "quickBooks",
    "frame5",
    "div15",
    "_5StarsOutOf6",
    "svg18",
    "svg19",
    "svg20",
    "svg21",
    "svg22",
    "facebook",
    "frame6",
    "group",
    "div16",
    "ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness",
    "ul2",
    "li3",
    "i",
    "iconCheckmark1Be90Bf8Svg",
    "symbols",
    "iconSuccess",
    "li4",
    "i2",
    "iconCheckmark1Be90Bf8Svg2",
    "symbols2",
    "iconSuccess2",
    "li5",
    "i3",
    "iconCheckmark1Be90Bf8Svg3",
    "symbols3",
    "iconSuccess3",
    "li6",
    "i4",
    "iconCheckmark1Be90Bf8Svg4",
    "symbols4",
    "iconSuccess4",
    "li7",
    "i5",
    "iconCheckmark1Be90Bf8Svg5",
    "symbols5",
    "iconSuccess5"
  ],
  article: [
    "article",
    "section",
    "div5",
    "div6",
    "form",
    "ul",
    "li",
    "inputemail",
    "workEmail",
    "li2",
    "inputpassword",
    "addAPassword",
    "div7",
    "button",
    "freeBox",
    "buttonafter",
    "div8",
    "div9",
    "div10",
    "logoSliderMaidMentorpng",
    "logoSliderLawncarlifepng",
    "logoSliderDmupng",
    "logoSliderBrolawspng",
    "div11",
    "div12",
    "_5StarsOutOf5",
    "svg3",
    "svg4",
    "svg5",
    "svg6",
    "svg7",
    "capterra",
    "frame3",
    "hpDesignRevised",
    "hpDesktop",
    "starRating",
    "div13",
    "_45StarsOutOf5",
    "svg8",
    "svg9",
    "svg10",
    "svg11",
    "svg12",
    "softwareAdvice",
    "frame4",
    "div14",
    "_45StarsOutOf6",
    "svg13",
    "svg14",
    "svg15",
    "svg16",
    "svg17",
    "quickBooks",
    "frame5",
    "div15",
    "_5StarsOutOf6",
    "svg18",
    "svg19",
    "svg20",
    "svg21",
    "svg22",
    "facebook",
    "frame6",
    "group",
    "div16",
    "ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness",
    "ul2",
    "li3",
    "i",
    "iconCheckmark1Be90Bf8Svg",
    "symbols",
    "iconSuccess",
    "li4",
    "i2",
    "iconCheckmark1Be90Bf8Svg2",
    "symbols2",
    "iconSuccess2",
    "li5",
    "i3",
    "iconCheckmark1Be90Bf8Svg3",
    "symbols3",
    "iconSuccess3",
    "li6",
    "i4",
    "iconCheckmark1Be90Bf8Svg4",
    "symbols4",
    "iconSuccess4",
    "li7",
    "i5",
    "iconCheckmark1Be90Bf8Svg5",
    "symbols5",
    "iconSuccess5"
  ],
  section: [
    "section",
    "div5",
    "div6",
    "form",
    "ul",
    "li",
    "inputemail",
    "workEmail",
    "li2",
    "inputpassword",
    "addAPassword",
    "div7",
    "button",
    "freeBox",
    "buttonafter",
    "div8",
    "div9",
    "div10",
    "logoSliderMaidMentorpng",
    "logoSliderLawncarlifepng",
    "logoSliderDmupng",
    "logoSliderBrolawspng",
    "div11",
    "div12",
    "_5StarsOutOf5",
    "svg3",
    "svg4",
    "svg5",
    "svg6",
    "svg7",
    "capterra",
    "frame3",
    "hpDesignRevised",
    "hpDesktop",
    "starRating",
    "div13",
    "_45StarsOutOf5",
    "svg8",
    "svg9",
    "svg10",
    "svg11",
    "svg12",
    "softwareAdvice",
    "frame4",
    "div14",
    "_45StarsOutOf6",
    "svg13",
    "svg14",
    "svg15",
    "svg16",
    "svg17",
    "quickBooks",
    "frame5",
    "div15",
    "_5StarsOutOf6",
    "svg18",
    "svg19",
    "svg20",
    "svg21",
    "svg22",
    "facebook",
    "frame6",
    "group",
    "div16",
    "ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness",
    "ul2",
    "li3",
    "i",
    "iconCheckmark1Be90Bf8Svg",
    "symbols",
    "iconSuccess",
    "li4",
    "i2",
    "iconCheckmark1Be90Bf8Svg2",
    "symbols2",
    "iconSuccess2",
    "li5",
    "i3",
    "iconCheckmark1Be90Bf8Svg3",
    "symbols3",
    "iconSuccess3",
    "li6",
    "i4",
    "iconCheckmark1Be90Bf8Svg4",
    "symbols4",
    "iconSuccess4",
    "li7",
    "i5",
    "iconCheckmark1Be90Bf8Svg5",
    "symbols5",
    "iconSuccess5"
  ],
  div5: ["div5"],
  div6: [
    "div6",
    "form",
    "ul",
    "li",
    "inputemail",
    "workEmail",
    "li2",
    "inputpassword",
    "addAPassword",
    "div7",
    "button",
    "freeBox",
    "buttonafter",
    "div8",
    "div9",
    "div10",
    "logoSliderMaidMentorpng",
    "logoSliderLawncarlifepng",
    "logoSliderDmupng",
    "logoSliderBrolawspng",
    "div11",
    "div12",
    "_5StarsOutOf5",
    "svg3",
    "svg4",
    "svg5",
    "svg6",
    "svg7",
    "capterra",
    "frame3",
    "hpDesignRevised",
    "hpDesktop",
    "starRating",
    "div13",
    "_45StarsOutOf5",
    "svg8",
    "svg9",
    "svg10",
    "svg11",
    "svg12",
    "softwareAdvice",
    "frame4",
    "div14",
    "_45StarsOutOf6",
    "svg13",
    "svg14",
    "svg15",
    "svg16",
    "svg17",
    "quickBooks",
    "frame5",
    "div15",
    "_5StarsOutOf6",
    "svg18",
    "svg19",
    "svg20",
    "svg21",
    "svg22",
    "facebook",
    "frame6",
    "group"
  ],
  form: [
    "form",
    "ul",
    "li",
    "inputemail",
    "workEmail",
    "li2",
    "inputpassword",
    "addAPassword",
    "div7",
    "button",
    "freeBox",
    "buttonafter",
    "div8",
    "div9"
  ],
  ul: [
    "ul",
    "li",
    "inputemail",
    "workEmail",
    "li2",
    "inputpassword",
    "addAPassword"
  ],
  li: ["li", "inputemail", "workEmail"],
  inputemail: ["inputemail"],
  workEmail: ["workEmail"],
  li2: ["li2", "inputpassword", "addAPassword"],
  inputpassword: ["inputpassword"],
  addAPassword: ["addAPassword"],
  div7: ["div7", "button", "freeBox", "buttonafter", "div8", "div9"],
  button: ["button", "freeBox", "buttonafter"],
  freeBox: ["freeBox", "buttonafter"],
  buttonafter: ["buttonafter"],
  div8: ["div8", "div9"],
  div9: ["div9"],
  div10: [
    "div10",
    "logoSliderMaidMentorpng",
    "logoSliderLawncarlifepng",
    "logoSliderDmupng",
    "logoSliderBrolawspng"
  ],
  logoSliderMaidMentorpng: ["logoSliderMaidMentorpng"],
  logoSliderLawncarlifepng: ["logoSliderLawncarlifepng"],
  logoSliderDmupng: ["logoSliderDmupng"],
  logoSliderBrolawspng: ["logoSliderBrolawspng"],
  div11: [
    "div11",
    "div12",
    "_5StarsOutOf5",
    "svg3",
    "svg4",
    "svg5",
    "svg6",
    "svg7",
    "capterra",
    "frame3",
    "hpDesignRevised",
    "hpDesktop",
    "starRating",
    "div13",
    "_45StarsOutOf5",
    "svg8",
    "svg9",
    "svg10",
    "svg11",
    "svg12",
    "softwareAdvice",
    "frame4",
    "div14",
    "_45StarsOutOf6",
    "svg13",
    "svg14",
    "svg15",
    "svg16",
    "svg17",
    "quickBooks",
    "frame5",
    "div15",
    "_5StarsOutOf6",
    "svg18",
    "svg19",
    "svg20",
    "svg21",
    "svg22",
    "facebook",
    "frame6",
    "group"
  ],
  div12: [
    "div12",
    "_5StarsOutOf5",
    "svg3",
    "svg4",
    "svg5",
    "svg6",
    "svg7",
    "capterra",
    "frame3",
    "hpDesignRevised",
    "hpDesktop",
    "starRating"
  ],
  _5StarsOutOf5: ["_5StarsOutOf5", "svg3", "svg4", "svg5", "svg6", "svg7"],
  svg3: ["svg3"],
  svg4: ["svg4"],
  svg5: ["svg5"],
  svg6: ["svg6"],
  svg7: ["svg7"],
  capterra: [
    "capterra",
    "frame3",
    "hpDesignRevised",
    "hpDesktop",
    "starRating"
  ],
  frame3: ["frame3", "hpDesignRevised", "hpDesktop", "starRating"],
  hpDesignRevised: ["hpDesignRevised", "hpDesktop", "starRating"],
  hpDesktop: ["hpDesktop", "starRating"],
  starRating: ["starRating"],
  div13: [
    "div13",
    "_45StarsOutOf5",
    "svg8",
    "svg9",
    "svg10",
    "svg11",
    "svg12",
    "softwareAdvice",
    "frame4"
  ],
  _45StarsOutOf5: ["_45StarsOutOf5", "svg8", "svg9", "svg10", "svg11", "svg12"],
  svg8: ["svg8"],
  svg9: ["svg9"],
  svg10: ["svg10"],
  svg11: ["svg11"],
  svg12: ["svg12"],
  softwareAdvice: ["softwareAdvice", "frame4"],
  frame4: ["frame4"],
  div14: [
    "div14",
    "_45StarsOutOf6",
    "svg13",
    "svg14",
    "svg15",
    "svg16",
    "svg17",
    "quickBooks",
    "frame5"
  ],
  _45StarsOutOf6: [
    "_45StarsOutOf6",
    "svg13",
    "svg14",
    "svg15",
    "svg16",
    "svg17"
  ],
  svg13: ["svg13"],
  svg14: ["svg14"],
  svg15: ["svg15"],
  svg16: ["svg16"],
  svg17: ["svg17"],
  quickBooks: ["quickBooks", "frame5"],
  frame5: ["frame5"],
  div15: [
    "div15",
    "_5StarsOutOf6",
    "svg18",
    "svg19",
    "svg20",
    "svg21",
    "svg22",
    "facebook",
    "frame6",
    "group"
  ],
  _5StarsOutOf6: ["_5StarsOutOf6", "svg18", "svg19", "svg20", "svg21", "svg22"],
  svg18: ["svg18"],
  svg19: ["svg19"],
  svg20: ["svg20"],
  svg21: ["svg21"],
  svg22: ["svg22"],
  facebook: ["facebook", "frame6", "group"],
  frame6: ["frame6", "group"],
  group: ["group"],
  div16: [
    "div16",
    "ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness",
    "ul2",
    "li3",
    "i",
    "iconCheckmark1Be90Bf8Svg",
    "symbols",
    "iconSuccess",
    "li4",
    "i2",
    "iconCheckmark1Be90Bf8Svg2",
    "symbols2",
    "iconSuccess2",
    "li5",
    "i3",
    "iconCheckmark1Be90Bf8Svg3",
    "symbols3",
    "iconSuccess3",
    "li6",
    "i4",
    "iconCheckmark1Be90Bf8Svg4",
    "symbols4",
    "iconSuccess4",
    "li7",
    "i5",
    "iconCheckmark1Be90Bf8Svg5",
    "symbols5",
    "iconSuccess5"
  ],
  ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness: [
    "ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness"
  ],
  ul2: [
    "ul2",
    "li3",
    "i",
    "iconCheckmark1Be90Bf8Svg",
    "symbols",
    "iconSuccess",
    "li4",
    "i2",
    "iconCheckmark1Be90Bf8Svg2",
    "symbols2",
    "iconSuccess2",
    "li5",
    "i3",
    "iconCheckmark1Be90Bf8Svg3",
    "symbols3",
    "iconSuccess3",
    "li6",
    "i4",
    "iconCheckmark1Be90Bf8Svg4",
    "symbols4",
    "iconSuccess4",
    "li7",
    "i5",
    "iconCheckmark1Be90Bf8Svg5",
    "symbols5",
    "iconSuccess5"
  ],
  li3: ["li3", "i", "iconCheckmark1Be90Bf8Svg", "symbols", "iconSuccess"],
  i: ["i", "iconCheckmark1Be90Bf8Svg", "symbols", "iconSuccess"],
  iconCheckmark1Be90Bf8Svg: [
    "iconCheckmark1Be90Bf8Svg",
    "symbols",
    "iconSuccess"
  ],
  symbols: ["symbols", "iconSuccess"],
  iconSuccess: ["iconSuccess"],
  li4: ["li4", "i2", "iconCheckmark1Be90Bf8Svg2", "symbols2", "iconSuccess2"],
  i2: ["i2", "iconCheckmark1Be90Bf8Svg2", "symbols2", "iconSuccess2"],
  iconCheckmark1Be90Bf8Svg2: [
    "iconCheckmark1Be90Bf8Svg2",
    "symbols2",
    "iconSuccess2"
  ],
  symbols2: ["symbols2", "iconSuccess2"],
  iconSuccess2: ["iconSuccess2"],
  li5: ["li5", "i3", "iconCheckmark1Be90Bf8Svg3", "symbols3", "iconSuccess3"],
  i3: ["i3", "iconCheckmark1Be90Bf8Svg3", "symbols3", "iconSuccess3"],
  iconCheckmark1Be90Bf8Svg3: [
    "iconCheckmark1Be90Bf8Svg3",
    "symbols3",
    "iconSuccess3"
  ],
  symbols3: ["symbols3", "iconSuccess3"],
  iconSuccess3: ["iconSuccess3"],
  li6: ["li6", "i4", "iconCheckmark1Be90Bf8Svg4", "symbols4", "iconSuccess4"],
  i4: ["i4", "iconCheckmark1Be90Bf8Svg4", "symbols4", "iconSuccess4"],
  iconCheckmark1Be90Bf8Svg4: [
    "iconCheckmark1Be90Bf8Svg4",
    "symbols4",
    "iconSuccess4"
  ],
  symbols4: ["symbols4", "iconSuccess4"],
  iconSuccess4: ["iconSuccess4"],
  li7: ["li7", "i5", "iconCheckmark1Be90Bf8Svg5", "symbols5", "iconSuccess5"],
  i5: ["i5", "iconCheckmark1Be90Bf8Svg5", "symbols5", "iconSuccess5"],
  iconCheckmark1Be90Bf8Svg5: [
    "iconCheckmark1Be90Bf8Svg5",
    "symbols5",
    "iconSuccess5"
  ],
  symbols5: ["symbols5", "iconSuccess5"],
  iconSuccess5: ["iconSuccess5"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  getjobbercomByHtmltodesignFreeVersion04022023234100Gmt5: "div";
  body: "div";
  loginNavBar: "div";
  div2: "div";
  a: "div";
  aafter: "div";
  div3: "div";
  call: "div";
  frame: "div";
  a2: "div";
  svg2: "div";
  frame2: "div";
  a3: "div";
  divafter: "div";
  main: "div";
  article: "div";
  section: "div";
  div5: "div";
  div6: "div";
  form: "div";
  ul: "div";
  li: "div";
  inputemail: "div";
  workEmail: "div";
  li2: "div";
  inputpassword: "div";
  addAPassword: "div";
  div7: "div";
  button: "div";
  freeBox: "div";
  buttonafter: "div";
  div8: "div";
  div9: "div";
  div10: "div";
  logoSliderMaidMentorpng: "div";
  logoSliderLawncarlifepng: "div";
  logoSliderDmupng: "div";
  logoSliderBrolawspng: "div";
  div11: "div";
  div12: "div";
  _5StarsOutOf5: "div";
  svg3: "div";
  svg4: "div";
  svg5: "div";
  svg6: "div";
  svg7: "div";
  capterra: "div";
  frame3: "div";
  hpDesignRevised: "div";
  hpDesktop: "div";
  starRating: "div";
  div13: "div";
  _45StarsOutOf5: "div";
  svg8: "div";
  svg9: "div";
  svg10: "div";
  svg11: "div";
  svg12: "div";
  softwareAdvice: "div";
  frame4: "div";
  div14: "div";
  _45StarsOutOf6: "div";
  svg13: "div";
  svg14: "div";
  svg15: "div";
  svg16: "div";
  svg17: "div";
  quickBooks: "div";
  frame5: "div";
  div15: "div";
  _5StarsOutOf6: "div";
  svg18: "div";
  svg19: "div";
  svg20: "div";
  svg21: "div";
  svg22: "div";
  facebook: "div";
  frame6: "div";
  group: "div";
  div16: "div";
  ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness: "div";
  ul2: "div";
  li3: "div";
  i: "div";
  iconCheckmark1Be90Bf8Svg: "div";
  symbols: "div";
  iconSuccess: "div";
  li4: "div";
  i2: "div";
  iconCheckmark1Be90Bf8Svg2: "div";
  symbols2: "div";
  iconSuccess2: "div";
  li5: "div";
  i3: "div";
  iconCheckmark1Be90Bf8Svg3: "div";
  symbols3: "div";
  iconSuccess3: "div";
  li6: "div";
  i4: "div";
  iconCheckmark1Be90Bf8Svg4: "div";
  symbols4: "div";
  iconSuccess4: "div";
  li7: "div";
  i5: "div";
  iconCheckmark1Be90Bf8Svg5: "div";
  symbols5: "div";
  iconSuccess5: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSignUpV2FigmaImport__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSignUpV2FigmaImport__VariantsArgs;
    args?: PlasmicSignUpV2FigmaImport__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSignUpV2FigmaImport__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSignUpV2FigmaImport__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSignUpV2FigmaImport__ArgProps,
          internalVariantPropNames: PlasmicSignUpV2FigmaImport__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicSignUpV2FigmaImport__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSignUpV2FigmaImport";
  } else {
    func.displayName = `PlasmicSignUpV2FigmaImport.${nodeName}`;
  }
  return func;
}

export const PlasmicSignUpV2FigmaImport = Object.assign(
  // Top-level PlasmicSignUpV2FigmaImport renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    getjobbercomByHtmltodesignFreeVersion04022023234100Gmt5: makeNodeComponent(
      "getjobbercomByHtmltodesignFreeVersion04022023234100Gmt5"
    ),
    body: makeNodeComponent("body"),
    loginNavBar: makeNodeComponent("loginNavBar"),
    div2: makeNodeComponent("div2"),
    a: makeNodeComponent("a"),
    aafter: makeNodeComponent("aafter"),
    div3: makeNodeComponent("div3"),
    call: makeNodeComponent("call"),
    frame: makeNodeComponent("frame"),
    a2: makeNodeComponent("a2"),
    svg2: makeNodeComponent("svg2"),
    frame2: makeNodeComponent("frame2"),
    a3: makeNodeComponent("a3"),
    divafter: makeNodeComponent("divafter"),
    main: makeNodeComponent("main"),
    article: makeNodeComponent("article"),
    section: makeNodeComponent("section"),
    div5: makeNodeComponent("div5"),
    div6: makeNodeComponent("div6"),
    form: makeNodeComponent("form"),
    ul: makeNodeComponent("ul"),
    li: makeNodeComponent("li"),
    inputemail: makeNodeComponent("inputemail"),
    workEmail: makeNodeComponent("workEmail"),
    li2: makeNodeComponent("li2"),
    inputpassword: makeNodeComponent("inputpassword"),
    addAPassword: makeNodeComponent("addAPassword"),
    div7: makeNodeComponent("div7"),
    button: makeNodeComponent("button"),
    freeBox: makeNodeComponent("freeBox"),
    buttonafter: makeNodeComponent("buttonafter"),
    div8: makeNodeComponent("div8"),
    div9: makeNodeComponent("div9"),
    div10: makeNodeComponent("div10"),
    logoSliderMaidMentorpng: makeNodeComponent("logoSliderMaidMentorpng"),
    logoSliderLawncarlifepng: makeNodeComponent("logoSliderLawncarlifepng"),
    logoSliderDmupng: makeNodeComponent("logoSliderDmupng"),
    logoSliderBrolawspng: makeNodeComponent("logoSliderBrolawspng"),
    div11: makeNodeComponent("div11"),
    div12: makeNodeComponent("div12"),
    _5StarsOutOf5: makeNodeComponent("_5StarsOutOf5"),
    svg3: makeNodeComponent("svg3"),
    svg4: makeNodeComponent("svg4"),
    svg5: makeNodeComponent("svg5"),
    svg6: makeNodeComponent("svg6"),
    svg7: makeNodeComponent("svg7"),
    capterra: makeNodeComponent("capterra"),
    frame3: makeNodeComponent("frame3"),
    hpDesignRevised: makeNodeComponent("hpDesignRevised"),
    hpDesktop: makeNodeComponent("hpDesktop"),
    starRating: makeNodeComponent("starRating"),
    div13: makeNodeComponent("div13"),
    _45StarsOutOf5: makeNodeComponent("_45StarsOutOf5"),
    svg8: makeNodeComponent("svg8"),
    svg9: makeNodeComponent("svg9"),
    svg10: makeNodeComponent("svg10"),
    svg11: makeNodeComponent("svg11"),
    svg12: makeNodeComponent("svg12"),
    softwareAdvice: makeNodeComponent("softwareAdvice"),
    frame4: makeNodeComponent("frame4"),
    div14: makeNodeComponent("div14"),
    _45StarsOutOf6: makeNodeComponent("_45StarsOutOf6"),
    svg13: makeNodeComponent("svg13"),
    svg14: makeNodeComponent("svg14"),
    svg15: makeNodeComponent("svg15"),
    svg16: makeNodeComponent("svg16"),
    svg17: makeNodeComponent("svg17"),
    quickBooks: makeNodeComponent("quickBooks"),
    frame5: makeNodeComponent("frame5"),
    div15: makeNodeComponent("div15"),
    _5StarsOutOf6: makeNodeComponent("_5StarsOutOf6"),
    svg18: makeNodeComponent("svg18"),
    svg19: makeNodeComponent("svg19"),
    svg20: makeNodeComponent("svg20"),
    svg21: makeNodeComponent("svg21"),
    svg22: makeNodeComponent("svg22"),
    facebook: makeNodeComponent("facebook"),
    frame6: makeNodeComponent("frame6"),
    group: makeNodeComponent("group"),
    div16: makeNodeComponent("div16"),
    ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness: makeNodeComponent(
      "ourFeaturesHelpYouOrganizeManageAndGrowYourBusiness"
    ),
    ul2: makeNodeComponent("ul2"),
    li3: makeNodeComponent("li3"),
    i: makeNodeComponent("i"),
    iconCheckmark1Be90Bf8Svg: makeNodeComponent("iconCheckmark1Be90Bf8Svg"),
    symbols: makeNodeComponent("symbols"),
    iconSuccess: makeNodeComponent("iconSuccess"),
    li4: makeNodeComponent("li4"),
    i2: makeNodeComponent("i2"),
    iconCheckmark1Be90Bf8Svg2: makeNodeComponent("iconCheckmark1Be90Bf8Svg2"),
    symbols2: makeNodeComponent("symbols2"),
    iconSuccess2: makeNodeComponent("iconSuccess2"),
    li5: makeNodeComponent("li5"),
    i3: makeNodeComponent("i3"),
    iconCheckmark1Be90Bf8Svg3: makeNodeComponent("iconCheckmark1Be90Bf8Svg3"),
    symbols3: makeNodeComponent("symbols3"),
    iconSuccess3: makeNodeComponent("iconSuccess3"),
    li6: makeNodeComponent("li6"),
    i4: makeNodeComponent("i4"),
    iconCheckmark1Be90Bf8Svg4: makeNodeComponent("iconCheckmark1Be90Bf8Svg4"),
    symbols4: makeNodeComponent("symbols4"),
    iconSuccess4: makeNodeComponent("iconSuccess4"),
    li7: makeNodeComponent("li7"),
    i5: makeNodeComponent("i5"),
    iconCheckmark1Be90Bf8Svg5: makeNodeComponent("iconCheckmark1Be90Bf8Svg5"),
    symbols5: makeNodeComponent("symbols5"),
    iconSuccess5: makeNodeComponent("iconSuccess5"),

    // Metadata about props expected for PlasmicSignUpV2FigmaImport
    internalVariantProps: PlasmicSignUpV2FigmaImport__VariantProps,
    internalArgProps: PlasmicSignUpV2FigmaImport__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSignUpV2FigmaImport;
/* prettier-ignore-end */
